### ISSUE TITLE
Error using pypia

### ISSUE THREAD

**Issue by samuellbeckett** [dagrha/pypia#28]
Hi
When I use pypia -i, I get this:
Traceback (most recent call last):
  File "/usr/local/bin/pypia", line 7, in <module>
    from pypia.pypia import main
  File "/usr/local/lib/python2.7/dist-packages/pypia/pypia.py", line 38, in <module>
    from queue import Queue
ImportError: No module named queue

Never had problem using your script in the past. Using KdE Nexus
Thanks

**Comment by dagrha** [comment]
Hi @samuellbeckett, thanks for opening an issue. How did you install pypia? You might try uninstalling that version (`pip uninstall pypia`) and try instead this command: `python3 -m pip install pypia` or `pip3 install pypia`. It looks like your machine is trying to use python2.7, so I suspect that might be causing the exception. Let me know how it goes.
