### ISSUE TITLE
openSUSE Tumbleweed Failed Execution

### ISSUE THREAD

**Issue by ghost** [dagrha/pypia#35]
pip install pypia seems to work fine:

linux-6ofw:/home/drhedberg # pip install pypia
Collecting pypia
  Downloading https://files.pythonhosted.org/packages/b7/ed/757b101d69dea59d0de1eb63aa4eb2aca06e17a98811549c4cc6961a012f/pypia-0.3.4.tar.gz
Installing collected packages: pypia
  Running setup.py install for pypia ... done
Successfully installed pypia-0.3.4

pypia -i however fails:

linux-6ofw:/home/drhedberg # pypia -i
Traceback (most recent call last):
  File "/usr/bin/pypia", line 11, in <module>
    load_entry_point('pypia==0.3.4', 'console_scripts', 'pypia')()
  File "/usr/lib/python3.6/site-packages/pypia/pypia.py", line 324, in main
    distro = Distro()
  File "/usr/lib/python3.6/site-packages/pypia/pypia.py", line 57, in __init__
    self.get_package_info()
  File "/usr/lib/python3.6/site-packages/pypia/pypia.py", line 71, in get_package_info
    self.required_packages = package_dict['required_packages'][self.distro]
KeyError: 'opensuse-tumbleweed'

**Comment by dagrha** [comment]
Thanks drhedberg 👍 . Fixed with https://github.com/dagrha/pypia/commit/e622e7a0084bc34f357296c2c3b8a68c92189096. Will update version at pypi shortly.
