### ISSUE TITLE
Add raspian OS support (Raspberry Pi)

### ISSUE THREAD

**Issue by Chambana** [dagrha/pypia#44]
$ pypia -i
Traceback (most recent call last):
  File "/usr/local/bin/pypia", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pypia/pypia.py", line 334, in main
    distro = Distro()
  File "/usr/local/lib/python3.5/dist-packages/pypia/pypia.py", line 58, in __init__
    self.get_package_info()
  File "/usr/local/lib/python3.5/dist-packages/pypia/pypia.py", line 75, in get_package_info
    logging.ERROR('{} is not yet supported.'.format(self.distro.upper()))
TypeError: 'int' object is not callable

**Comment by dagrha** [comment]
Thanks for reporting this traceback. Should have a fix shortly

**Comment by dagrha** [comment]
Raspbian support has been added with ee1645fd69f43bd743767dc661a1292bad56704a
This error you are having has been fixed with 80c5b831d0d6b90fde129bc51bea4e09f3397334

I will increment the version number and push the change to pypi.org
