### ISSUE TITLE
Unable to Connect - "client update needed"

### ISSUE THREAD

**Issue by Justinzobel** [dagrha/pypia#47]
Each connection has in brackets Client update needed when going via NetworkManager

Have tried several, none connect.

OS Solus 4.1

If I try via terminal I get
pypia -f
Pinging all PIA servers. This might take a few seconds...

ping: unknown host
ping: unknown host
ping: unknown host
ping: unknown host
ping: unknown host
ping: unknown host
ping: unknown host
ping: unknown host
ping: unknown host
ping: unknown host
ping: unknown host
ping: unknown host
ping: unknown host
Traceback (most recent call last):
  File "/usr/bin/pypia", line 11, in <module>
    load_entry_point('pypia==0.3.7', 'console_scripts', 'pypia')()
  File "/usr/lib/python3.7/site-packages/pypia/pypia.py", line 357, in main
    print(lat)
  File "/usr/lib/python3.7/site-packages/pypia/pypia.py", line 306, in __str__
    .format(self.ip_addresses[k], j[0], j[1], j[2], j[3],
IndexError: list index out of range

**Comment by saponace** [comment]
I confirm I have the same issue here.
If there is any details to give, I'd be more than happy to help.

Kernel version : 5.11.4
NetworkManager version : 1.30.0-2
Inputils version : s20200821
